[{"ContainerToolsException.Message":"golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:строка 253\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:строка 115\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:строка 418\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:строка 87","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"2","ContainerToolsException.CommandLine.ErrorOutput":"Container dockercompose8611608043351235670-cassandra-node3-1  Stopping\r\nContainer DataAccessService  Stopping\r\nContainer DataAccessService  Stopping\r\nContainer dockercompose8611608043351235670-cassandra-node3-1  Stopping\r\nContainer dockercompose8611608043351235670-cassandra-node2-1  Stopping\r\nContainer dockercompose8611608043351235670-cassandra-node2-1  Stopping\r\nContainer dockercompose8611608043351235670-cassandra-node1-1  Stopping\r\nContainer Gateway  Stopping\r\nContainer Gateway  Stopping\r\nContainer dockercompose8611608043351235670-cassandra-node1-1  Stopping\r\nContainer JiraScrapper  Stopping\r\nContainer JiraScrapper  Stopping\r\nContainer DataAccessService  Stopped\r\nContainer DataAccessService  Removing\r\nContainer dockercompose8611608043351235670-cassandra-node2-1  Stopped\r\nContainer dockercompose8611608043351235670-cassandra-node2-1  Removing\r\nContainer JiraScrapper  Stopped\r\nContainer JiraScrapper  Removing\r\nContainer DataAccessService  Removed\r\nContainer JiraScrapper  Removed\r\nContainer Gateway  Stopped\r\nContainer Gateway  Removing\r\nContainer Gateway  Removed\r\nContainer dockercompose8611608043351235670-cassandra-node3-1  Stopped\r\nContainer dockercompose8611608043351235670-cassandra-node3-1  Removing\r\nContainer dockercompose8611608043351235670-cassandra-node3-1  Removed\r\nContainer dockercompose8611608043351235670-cassandra-node2-1  Removed\r\nContainer dockercompose8611608043351235670-cassandra-node1-1  Stopped\r\nContainer dockercompose8611608043351235670-cassandra-node1-1  Removing\r\nContainer dockercompose8611608043351235670-cassandra-node1-1  Removed\r\npanic: runtime error: invalid memory address or nil pointer dereference\r\n[signal 0xc0000005 code=0x0 addr=0x28 pc=0x1b205b5]\r\ngoroutine 30 [running]:\r\ngithub.com/docker/compose/v2/pkg/compose.(*composeService).getServiceImages(0x1c992c0, {0x1, 0x0, 0x0, {0xc0000a6160, 0x5}, 0x0}, {0xc0000a20e0, 0x20})\r\n\tgithub.com/docker/compose/v2/pkg/compose/down.go:149 +0x75\r\ngithub.com/docker/compose/v2/pkg/compose.(*composeService).ensureImagesDown(0xc0004dc000, {0x200b2c8, 0xc000048420}, {0xc0000a20e0, 0x20}, {0x1, 0x0, 0x0, {0xc0000a6160, 0x5}, ...}, ...)\r\n\tgithub.com/docker/compose/v2/pkg/compose/down.go:119 +0xc8\r\ngithub.com/docker/compose/v2/pkg/compose.(*composeService).down(0xc0004dc000, {0x200b2c8, 0xc000048420}, {0xc0000a20e0, 0x20}, {0x1, 0x0, 0x0, {0xc0000a6160, 0x5}, ...})\r\n\tgithub.com/docker/compose/v2/pkg/compose/down.go:85 +0x4b4\r\ngithub.com/docker/compose/v2/pkg/compose.(*composeService).Down.func1({0x200b2c8, 0xc000048420})\r\n\tgithub.com/docker/compose/v2/pkg/compose/down.go:39 +0x85\r\ngithub.com/docker/compose/v2/pkg/progress.Run.func1({0x200b2c8, 0xc000048420})\r\n\tgithub.com/docker/compose/v2/pkg/progress/writer.go:61 +0x27\r\ngithub.com/docker/compose/v2/pkg/progress.RunWithStatus.func2()\r\n\tgithub.com/docker/compose/v2/pkg/progress/writer.go:82 +0x87\r\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\r\n\tgolang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67\r\ncreated by golang.org/x/sync/errgroup.(*Group).Go\r\n\tgolang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92"},{"ContainerToolsException.Message":"Для работы Средств Visual Studio для контейнеров необходимо запустить Docker перед сборкой, отладкой или запуском контейнерного проекта.  Дополнительные сведения см. на странице https://aka.ms/DockerToolsTroubleshooting.","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: error during connect: This error may indicate that the docker daemon is not running.: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Ddockercompose8611608043351235670%22%3Atrue%7D%7D&limit=0\": open //./pipe/docker_engine: The system cannot find the file specified.\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:строка 253\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:строка 104\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:строка 418\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:строка 87\r\nКод ошибки: DT1001\r\nСерьезность: Error\r\nКомандная строка: docker-compose  -f \"C:\\REPOS\\ASS\\SuperProject\\DotnetServices\\docker-compose.yml\" -f \"C:\\REPOS\\ASS\\SuperProject\\DotnetServices\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose8611608043351235670 --ansi never kill\r\nКод завершения команды: 1\r\nВыходные данные команды: \r\nОшибка команды: error during connect: This error may indicate that the docker daemon is not running.: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Ddockercompose8611608043351235670%22%3Atrue%7D%7D&limit=0\": open //./pipe/docker_engine: The system cannot find the file specified.\r\n"}]